
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 4;
  public static final int LT = 8;
  public static final int NE = 13;
  public static final int ELSE = 25;
  public static final int LS = 17;
  public static final int PLUS = 2;
  public static final int INT = 21;
  public static final int RS = 18;
  public static final int LP = 15;
  public static final int WHILE = 23;
  public static final int SEMI = 6;
  public static final int RP = 16;
  public static final int RETURN = 26;
  public static final int IF = 24;
  public static final int GT = 9;
  public static final int ID = 28;
  public static final int LE = 10;
  public static final int NUM = 27;
  public static final int LC = 19;
  public static final int RC = 20;
  public static final int COMMA = 7;
  public static final int EOF = 0;
  public static final int DIVIDE = 5;
  public static final int GE = 11;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int ASSIGN = 14;
  public static final int EQ = 12;
  public static final int VOID = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "SEMI",
  "COMMA",
  "LT",
  "GT",
  "LE",
  "GE",
  "EQ",
  "NE",
  "ASSIGN",
  "LP",
  "RP",
  "LS",
  "RS",
  "LC",
  "RC",
  "INT",
  "VOID",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "NUM",
  "ID"
  };
}

